spring.datasource.password=190306
security.jwt.secret=oficina_da_festa_secret_key_1234
device.masterKey=CATRACA_OFICINA_DA_FESTA_DEVICE_1234

# OpenRouteService
delivery.ors.api-key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjhhZjNjNjYyODA0MTRkZGViNWZhYWQwOTgxMGUzYTI1IiwiaCI6Im11cm11cjY0In0=
delivery.ors.origin-address=R. Jequirituba, 29 - Jardim Colonial, São Paulo - SP, 04822-000
